version: '3.4'

services:
  ledgerxrpvoting:
    image: ledgerxrpvoting
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1234:1234
