name: Docker Image ACR Build and Push
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: ['src/VotingOnTheBlockChain/Voting/*']
env:
  IMAGE_NAME: voting-ledgernano
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Read version from file
      id: tag
      uses: juliangruber/read-file-action@v1
      with:
        path: src/VotingOnTheBlockChain/Voting/version.txt  
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
       push: true
       build-args: |
         version=${{ steps.tag.outputs.tag }}
       tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
