name: Docker Image ACR Build and Push
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: ['src/VotingOnTheBlockChain/Voting/*']
env:
  IMAGE_NAME: voting-ledgernano
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read version from file
        id: tag
        uses: juliangruber/read-file-action@v1
        with:
          path: src/VotingOnTheBlockChain/Voting/version.txt
      - name: Echo version.txt
        run: echo "${{ steps.tag.outputs.content }}"
      - name: Log into registry
        uses: azure/docker-login@v1
        with:
          login-server: servian.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build src/VotingOnTheBlockChain/Voting/* -t servian.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.content }}
          docker push servian.azurecr.io servian.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.content }}
