name: sample
on:
  workflow_dispatch:
env:
  IMAGE_NAME: voting-ledgernano
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SERVIAN_1_MPN }}
      - name: check container environment existance
        id: environmentexistance
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp env show -n ${{ env.CONTAINERAPP_ENV }} -g ${{ env.RESOURCE_GROUP }}           
        continue-on-error: true    
      - name: Echo all
        if: ${{ failure() }}
        id: echo
        run: echo "FAILURE"
              
          
      
